services:
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    command: redis-server --requirepass 090224T@n
    networks:
      - t-short-url

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    networks:
      - t-short-url

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    ports:
      - "9091:9091"
      - "19091:19091"
      - "29091:29091"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9091,CONTROLLER://:19091,EXTERNAL://:29091"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9091,EXTERNAL://localhost:29091"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:19091"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - t-short-url
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8999:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9091
    networks:
      - t-short-url

volumes:
  redisinsight:

networks:
  t-short-url:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1