spring:
  application:
    name: t-shorten-url
  mongodb:
    uri: mongodb://tanle92:090224Tan@localhost:27017/t-shorten-url?authSource=admin

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s

      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
      password: 090224T@n
  kafka:
    bootstrap-servers: localhost:29091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: clickEvent:com.tanle.t_shorten_url.event.ClickEvent

    consumer:
      group-id: analyzed-group
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: clickEvent:com.tanle.t_shorten_url.event.ClickEvent
      auto-offset-reset: latest

worker:
  id: 1

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

app:
  kafka:
    short-analyzed-topic: short-analyzed-topic